@startuml

left to right direction
actor User as U
rectangle WhatsApp {
  U -- (Daftar) 
  U -- (Buat Grup)
  U -- (Chat dengan Kontak)
  U -- (Profile Setting)
  U -- (Kelola Akun)
 

  (Daftar) --> (Buat Profil)
  (Daftar) --> (Verifikasi OTP Nomor Telepon)
  (Daftar) --> (Masukkan Nomor Telepon)

  (Chat dengan Kontak) --> (Kirim Lokasi)
  (Chat dengan Kontak) --> (Kirim Emoji/Stiker)
  (Chat dengan Kontak) --> (Kirim Img/Video/Audio)
  (Chat dengan Kontak) --> (Kirim Teks)
  
  (Profile Setting) --> (Edit Foto Profile)
  (Profile Setting) --> (Edit Info Status)
  
  (Kelola Akun) --> (Hapus Akun)
  (Kelola Akun) --> (Ubah Nomer)
  (Kelola Akun) --> (Privasi Setting)


}

@enduml
